<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUDxwZ13\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUDxwZ13/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUDxwZ13.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUDxwZ13\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUDxwZ13\appProdProjectContainer(array(
    'container.build_hash' => 'UDxwZ13',
    'container.build_id' => '7cf91876',
    'container.build_time' => 1534195126,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUDxwZ13');
